#pragma once
#define DW_GUI_VERSION_MAJOR 0
#define DW_GUI_VERSION_MINOR 0
#define DW_GUI_VERSION_PATCH 7
#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)
#define DW_GUI_VERSION "v." STR(DW_GUI_VERSION_MAJOR) "." STR(DW_GUI_VERSION_MINOR) "." STR(DW_GUI_VERSION_PATCH)

#define DW_GUI_AUTHOR "Erik Wernersson"
